### ISSUE TITLE
Please start this app on android 13 

### ISSUE THREAD

**Issue by Kryczyk** [simondankelmann/Bluetooth-LE-Spam#60] opened 2023-11-05 09:31 UTC
This app not work on android 13

**Comment by ha2ked** [comment] 2023-11-05 09:56
It normally does

**Comment by Sewo0018** [comment] 2023-11-06 13:37
Xiaomi 11T Pro Android 13 not working

**Comment by DerGoogler** [comment] 2023-11-06 13:42
The app is targeted to Android 14. But the support is unknown/unconfirmed.

**Comment by simondankelmann** [comment] 2023-11-06 15:07
As this is a duplicate of:

https://github.com/simondankelmann/Bluetooth-LE-Spam/issues/29

i will close it here :)

**Closed by simondankelmann** 2023-11-06 15:07 UTC
Labels: duplicate

**Comment by skjose0705** [comment] 2023-11-13 12:37
I'm using android 13 and it works
