### ISSUE TITLE
The app stops itself after executing

### ISSUE THREAD

**Issue by leirrie** [simondankelmann/Bluetooth-LE-Spam#41] opened 2023-11-04 02:14 UTC

**Comment by ha2ked** [comment] 2023-11-04 08:52
Please give more information

**Comment by simondankelmann** [comment] 2023-11-06 14:57
@leirrie 

Please provide some more Information like logs or specific error message. 
Otehrwise, if the Problem is solved, please close this Issue

**Comment by simondankelmann** [comment] 2023-11-13 17:05
Closed for now as there is no further Information

**Closed by simondankelmann** 2023-11-13 17:05 UTC
Labels: bug
